
module.exports = {
  
  GERAL_ERROR: 101,
  ACCESS_DENIED_ERROR: 111,
  NON_EXISTENT_USER_ERROR: 112,
  INCORRECT_PASSWORD_ERROR: 113,
  LOGIN_SUCCESSFUL: 211,

  OPENING_GET_ALL_SUCCESSFUL: 221,
  OPENING_CLEAR_SUCCESSFUL: 222,
  OPENING_DELETE_SUCCESSFUL: 223,
  OPENING_CREATE_SUCCESSFUL: 224,

  USER_GET_ALL_SUCCESSFUL: 231,

  PROFILE_IMAGE_GET_ERROR: 131,
  PROFILE_IMAGE_GET_SUCCESSFUL: 231,

}